name: Run FF Script

on:
  workflow_dispatch: # এটা বাটন তৈরি করবে যাতে আপনি যখন খুশি স্টার্ট করতে পারেন

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # ৫ ঘণ্টা ৫০ মিনিট পর অটো বন্ধ হবে (৬ ঘণ্টার লিমিট সেফ রাখার জন্য)

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # আপনার প্রয়োজন হলে ৩.১১ বা ৩.৯ দিতে পারেন

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Main Script
      run: |
        python main.py
